name: the_third_bookkeeping
description: "The third bookkeeping"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.6
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  fluttertoast: ^8.0.9
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1
  url_launcher: ^6.1.0


flutter:
  fonts:
    - family: plus
      fonts:
        - asset: assets/fonts/plus_jakarta_sans_bold.ttf


  uses-material-design: true
  assets:
    - assets/img/
    - assets/fonts/
