class AccountData {
  static List<String> expensesImage = [
    'assets/img/ic_dining.webp',
    'assets/img/ic_transportation.webp',
    'assets/img/ic_communication.webp',
    'assets/img/ic_housing.webp',
    'assets/img/ic_daily.webp',
    'assets/img/ic_shopping.webp',
    'assets/img/ic_entertainment.webp',
    'assets/img/ic_fitness.webp',
    'assets/img/ic_learning.webp',
    'assets/img/ic_medical.webp',
    'assets/img/ic_family.webp',
    'assets/img/ic_gifts.webp',
    'assets/img/ic_finance.webp',
    'assets/img/ic_pets.webp',
    'assets/img/ic_others.webp',
  ];
  static List<String> expensesText = [
    'Dining',
    'Transportation',
    'Communication',
    'Housing',
    'Daily',
    'Shopping',
    'Entertainment',
    'Fitness',
    'Learning',
    'Medical',
    'Family',
    'Gifts',
    'Finance',
    'Pets',
    'Others',
  ];


  static List<String> incomeText = [
    'Salary',
    'Bonus',
    'Part-Time Job',
    'Side Business',
    'FinanceIncome',
    'Rent',
    'OthersIncome',
  ];
  static List<String> incomeImage = [
    'assets/img/ic_salary.webp',
    'assets/img/ic_bonus.webp',
    'assets/img/ic_part.webp',
    'assets/img/ic_side_business.webp',
    'assets/img/ic_finance_in.webp',
    'assets/img/ic_rent.webp',
    'assets/img/ic_others_in.webp',
  ];



  static List<String> dataTextZong = [
    'Dining',
    'Transportation',
    'Communication',
    'Housing',
    'Daily',
    'Shopping',
    'Entertainment',
    'Fitness',
    'Learning',
    'Medical',
    'Family',
    'Gifts',
    'Finance',
    'Pets',
    'Others',
    'Salary',
    'Bonus',
    'Part-Time Job',
    'Side Business',
    'FinanceIncome',
    'Rent',
    'OthersIncome',
  ];

  static List<String> dataImageZong = [
    'assets/img/ic_dining.webp',
    'assets/img/ic_transportation.webp',
    'assets/img/ic_communication.webp',
    'assets/img/ic_housing.webp',
    'assets/img/ic_daily.webp',
    'assets/img/ic_shopping.webp',
    'assets/img/ic_entertainment.webp',
    'assets/img/ic_fitness.webp',
    'assets/img/ic_learning.webp',
    'assets/img/ic_medical.webp',
    'assets/img/ic_family.webp',
    'assets/img/ic_gifts.webp',
    'assets/img/ic_finance.webp',
    'assets/img/ic_pets.webp',
    'assets/img/ic_others.webp',
    'assets/img/ic_salary.webp',
    'assets/img/ic_bonus.webp',
    'assets/img/ic_part.webp',
    'assets/img/ic_side_business.webp',
    'assets/img/ic_finance_in.webp',
    'assets/img/ic_rent.webp',
    'assets/img/ic_others_in.webp',
  ];
}
